version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app

  test:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - ./:/app
    command: ["npm", "run", "test"]